### ISSUE TITLE
Don't use nightly feature interseprse for joining a vec

### ISSUE THREAD

**Issue by cobalthex** [juntyr/const-type-layout#14]
vec::join(",") can be used to join a vec w/ a separator.
https://doc.rust-lang.org/std/iter/struct.Intersperse.html is not needed (and almost certainly more overhead)

**Comment by juntyr** [comment]
Thanks for the suggestion! This was fixed in https://github.com/juntyr/const-type-layout/commit/69172744d7b7a839d741d3321ee7bcc2015dab3d
